import type { PackagePage } from '../../../types';
import { partialHydrationHocConfigExample } from './with-hydration.snippets';

export const withHydrationPage: PackagePage = {
  blocks: [
    {
      codeExamples: [
        {
          code: partialHydrationHocConfigExample,
          label: 'withHydration options',
          language: 'tsx',
        },
      ],
      bullets: [
        'Pass `modifiers` to add CSS classes to the wrapper div.',
        'Pass `attributes` to add custom HTML attributes like `data-testid`.',
        'Set a stable `displayName` on the wrapped component so `withHydration()` can write the correct `data-component` value.',
      ],
      id: 'hoc-options',
      paragraphs: [
        'The `withHydration` HOC accepts an optional configuration object to customize the wrapper `div` it generates. It uses the original component `displayName` for `data-component`, then applies your additional classes and attributes without requiring another wrapper element.',
      ],
      title: 'Wrapper Configuration',
    },
  ],
  eyebrow: 'Guides',
  id: 'with-hydration',
  intro: 'Customize the HTML wrapper generated by the withHydration HOC.',
  summary: 'withHydration options.',
  title: 'withHydration Options',
};
